/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ian' at '10/20/15 10:44 AM' with Gradle 2.5-rc-2
 *
 * @author Ian, @date 10/20/15 10:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
